### ISSUE TITLE
code: Follow-up work for node implementation

### ISSUE THREAD

**Issue by romac** [circlefin/malachite#178]
- [x] Update flow diagram to match ADR and include in ADR
- [x] Remove dependency on `ProposerSelector` from the `Driver` (#179)
- [x] Implement CAL and Proposal Builder actors (which will eventually use the Starknet Context) (#180)
- [x] Let validator set change between heights
- [x] Proposal builder must gossip block parts
- [x] Add `init` and `start` commands
- [x] Add config file (#134)
- [ ] Add persistent peers to GossipSub
- [ ] Move each actor into its respective crate
- [ ] Investigate message ordering guarantees of GossipSub ([ref](https://github.com/informalsystems/malachite/pull/167#issuecomment-2027967980))
