### ISSUE TITLE
spec: Node synchronization

### ISSUE THREAD

**Issue by cason** [circlefin/malachite#260]
This issue aims to track the multiple threads of work related to the synchronization of nodes in the consensus protocol.

We discuss protocols and solutions to implement the strong communication primitive adopted by Tendermint, described in the next section, in a variety of scenarios where nodes may lack messages to progress in the consensus protocol.

###  Background

The theoretical [Tendermint consensus algorithm](https://github.com/informalsystems/malachite/blob/main/docs/The%20latest%20gossip%20on%20BFT%20consenus.pdf) is designed for a system model that includes the following, strong communication assumption, which is a form of Byzantine Reliable Broadcast and timeless guarantees from the partial synchronous model: 

> _Gossip communication_: If a correct process `p` sends some message `m` at time `t`, all correct processes will receive `m` before `max{t, GST } + ∆`. Furthermore, if a correct process `p` receives some message `m` at time `t`, all correct processes will receive `m` before `max{t, GST } + ∆`.

If we remove the timing guarantees (`t`, `∆`, and `GST`), the assumption can be written as two liveness properties:

1. If a correct process sends a message, then every correct process eventually delivers that message
2. If a correct process delivers a message, then every correct process eventually delivers that message

Property 2. has the interesting aspect that it also applies to messages produced by Byzantine agents. Byzantine agents may equivocate, sending multiple distinct messages in the same round step, but if a correct process relies on a message from a Byzantine process to achieve progress, than this message *must* be delivered to every other correct process. The complexity related to the requirement of reliably delivering votes from Byzantine processes is discussed in https://github.com/informalsystems/malachite/issues/103.

### Scenarios

An initial list of scenarios and solutions to address are:

- [x] #235
- [x] How to catch-up nodes that are behind on the consensus protocol: #425
- [ ] Define a strategy to store messages from future rounds and heights of consensus
   - Some general ideas are in the consensus English spec: [future rounds](https://github.com/informalsystems/malachite/tree/main/specs/english/consensus#future-rounds) and [different heights](https://github.com/informalsystems/malachite/tree/main/specs/english/consensus#different-heights)
- [ ] #212, namely how to prevent abuses from malicious actors
- [ ] #316
- [ ] #312

**Comment by cason** [comment]
Notice that https://github.com/informalsystems/malachite/issues/235 is part of the solution, but a more comprehensive design is required to handle scenarios where equivocation can prevent decisions from being reached.

**Comment by adizere** [comment]
I suspect this is outdated since the redesign of the liveness sub-protocols. Should we keep it open, or which sub-issues are still relevant?

**Comment by cason** [comment]
> I suspect this is outdated since the redesign of the liveness sub-protocols

Where are them documented?
