### ISSUE TITLE
spec: Consensus misbehaviour

### ISSUE THREAD

**Issue by ancazamfir** [circlefin/malachite#340]
cc @cason @josef-widder 
We have started to code detection of some misbehaviour and evidence collection (checked below). We need a clear specification, in particular, to start with, one based on existing conensus messages (proposal, prevote, precommit). We can enhance when we have more notifications.

@romac and I were looking at the algorithm and discussed the items below. Some could be wrong, maybe others can be added. It would be great to have a correct specification along these lines. English would be great to start with 😄 

Following shows seen messages, assume all messages are for the same height.

#### Validator misbehaviour:
- [x] `proposal(V, r, v, *)`, `V` is non-proposer 

#### Equivocation:

- [x] `proposal(P, r, v, *), proposal(P, r, v', *)` 
  -`P` should not propose two different values in same round

- [x] `prevote(V, r, v), prevote(V, r, v')` 
  - `V` should not prevote two different values in same round, notice that either `v` or `v'` can be `nil`

- [x] `precommit(V, r, v), precommit(V, r, v')` 
  - `V` should not precommit two different values in the same round, notice that either `v` or `v'` can be `nil`

#### Potential amnesia attacks

By potential we mean that there are correct scenarios where this can happen. We will add to each point the specific correct scenario when this can happen and how the validator could proof its correct behavior:

- [x] `proposal(P, r, v, *), precommit(P, r', v')` with `r' < r`, non-nil values 
  - `P` should have valid `v'` and propose that, doesn't follow `L16`
  - However it is possible that in a round `r"` with `r' < r" < r`, `P` has received `2f + 1` prevotes for `v`, thus updating its `validValuep`, but this happened after it has already produced its precommit for round `r"`, therefore it did not update its `lockedValuep`

- [x] `prevote(V, r, v), precommit(V, r', v')` with `r'< r`, non-nil values
  - `V` should have locked on `v'`, doesn't follow `L23` (`lockedValuep == v`)
  - This is valid as long as there is no `precommit(V, r", v')` with `r' < r" < r`

- [x] `precommit(V, r, v), precommit(V, *, v')`, non-nil values 
  - `V` should not precommit on two different values within a height
  - Similarly to the previous scenarios, it is possible that the validator has updated its locked value at a round `r"` with `r' < r" < r`, which would justify the change on the value it precommits.

TODO - add related issues
