### ISSUE TITLE
feat: Open-source the repository

### ISSUE THREAD

**Issue by romac** [circlefin/malachite#375]
### Code

- [x] #439 
- [x] #607 
- [x] #616 
- [x] https://github.com/informalsystems/malachite/issues/606
- [x] https://github.com/informalsystems/malachite/pull/525
- [x] https://github.com/informalsystems/malachite/issues/373
- [x] https://github.com/informalsystems/malachite/issues/652
- [x] #651 + docs 

### Examples

- [x] Add example channel-based app @greg-szabo

### General documentation

- [x] Add a `SECURITY.md` file
- [x] #697 (`ARCHITECTURE.md` file)
- [x] Add a `LICENSE` file
- [x] Add a `CODE_OF_CONDUCT.md` file
- [x] #558
- [x] Pimp up the readme.md @adizere 
  - [x] Add a WIP (no crates yet) disclaimer
  - [x] Have a logo + banners
  - [ ] Add link to Farcaster application

### Code

- [ ] Draw new diagrams for actor system and flow within
- [ ] https://github.com/informalsystems/malachite/issues/431
- [x] https://github.com/informalsystems/malachite/issues/320
- [x] #466
- [ ] https://github.com/informalsystems/malachite/issues/376

#### App examples (in priority order)

- [ ] Prerequisites
  - [x] https://github.com/informalsystems/malachite/issues/459 @greg-szabo 
  - [ ] https://github.com/informalsystems/malachite/discussions/549
- [ ] https://github.com/informalsystems/malachite/issues/418
- [ ] Out-of-process (gRPC) KV app @romac @greg-szabo
- [x] #649

#### QA @greg-szabo 
- [ ] multi DC setup, 100 nodes - generate QA report

### Specs

- [x] #425
- [x] #250
- [ ] #468
- [x] #408

See [open-source](https://github.com/informalsystems/malachite/labels/open-source)
