### ISSUE TITLE
code: MVP for Blocksync

### ISSUE THREAD

**Issue by ancazamfir** [circlefin/malachite#439]
Following the spec #408

![Consensus Sync Arch (1)](https://github.com/user-attachments/assets/9e1d63a8-250b-42ba-a51a-99ec194c19f6)

To be done in #440
- create new blocksync actor
- add Status message, send it on `/status` topic
- add `BlockSyncRequest`/ `BlockSyncResponse` messages, use the libp2p request/ response to peer
- at every height save the decided block along with the proposal and commits, needed to be able to respond to sync block requests and process responses
- add tx type for canonical commits
- add Certificate message, collection of commits
- when receiving the synced block, use (new method in) the value builder to execute the block and return the `ProposedValue(h, r, v, validity)`

To be done in a second iteration:
- [x] Add timeouts
- [ ] Design spec for blocksync
- [ ] Add block_parts/ streaming for the synced block to deal with libp2p payload limits
- [ ] Optimistic future block requests
- [ ] Loadbalance requests across high peers
- [ ] Certificate should include (value, aggregated_signature). For schemes that don't support aggregation natively (ed25519 and ECDSA) the signature is a collection of commits. Ideally add BLS signatures. Add `aggregate()` and `verify_aggregated_signature()` methods. When verifying the aggregated_signature check the signature and weight, send a new `proposalAndQuorum` msg to the driver potentially bypassing the vote keeper. 

```[tasklist]
### Tasks
```
