### ISSUE TITLE
project: Rename project to `Malakite`

### ISSUE THREAD

**Issue by romac** [circlefin/malachite#491]
There is already a project name `Malachite` (https://malachite.rs) who owns a bunch of crates with the `malachite` prefix, such as `malachite`, `malachite-base`, etc.

It would therefore be confusing if we were to release our crates with the same prefix.

Instead, I propose that we rename the project to *Malakite*. I've already grabbed the `malakite` name on crates.io for this purpose.
```[tasklist]
### Tasks
- [ ] Adi - inform Joan
- [ ] Adi - snatch malakite.rs
- [ ] Adi - rename knowledge bases and slack channels
- [ ] Romain - rename Github repo
```
