### ISSUE TITLE
Tendermint in Rust for Starkware Decentralized Protocol v0.1

### ISSUE THREAD

**Issue by ancazamfir** [circlefin/malachite#6]
This is the meta issue for first phase of Tendermint in Rust consensus protocol impementation.

## Tasks
- [x] Specs
    - [x] English spec: started under [this PR](https://github.com/cometbft/knowledge-base/pull/18). Should move here, open issue and link the PRs.
       - closed in https://github.com/informalsystems/malachite/pull/89
    - [x] Quint spec: [existing spec](https://github.com/informalsystems/quint/tree/main/examples/cosmos/tendermint)
       - all specs are now in https://github.com/informalsystems/malachite/tree/main/Specs/Quint
- [x] Design and Implementation
    - [x] #33
    - [x] #49
       - [x] https://github.com/informalsystems/malachite/pull/1
    - [x] https://github.com/informalsystems/malachite/pull/8
    - [x] https://github.com/informalsystems/malachite/pull/7
    - [x] https://github.com/informalsystems/malachite/pull/5
    - [x] https://github.com/informalsystems/malachite/pull/4
    - [x] https://github.com/informalsystems/malachite/pull/3
    - [x] CI - https://github.com/informalsystems/malachite/pull/2    
- [x] ~~Instantiation for concrete chains~~ **-> Move to phase 2**
    ~~- [ ] #47~~
    ~~- [ ] #48~~
- [ ] MBT tests (in a new crate `malachite-mbt`)
    - [x] #44
    - [x] #45
    - [ ] #46 (postponed to phase2)
