### ISSUE TITLE
code: WAL for crash recovery with f+1 faulty

### ISSUE THREAD

**Issue by romac** [circlefin/malachite#607]
See https://github.com/informalsystems/malachite/issues/469

## Tasks

- [x] https://github.com/informalsystems/malachite/pull/608
- [x] https://github.com/informalsystems/malachite/pull/613
- [x] https://github.com/informalsystems/malachite/pull/633
