### ISSUE TITLE
spec: Collection of open points

### ISSUE THREAD

**Issue by josef-widder** [circlefin/malachite#95]
This is perhaps a bit unstructured. But while reviewing recent changes and PRs things come to my mind.

- [x] #151
- [x] #155
- [x] https://github.com/informalsystems/malachite/issues/81: Check what precisely is happening. I guess we can capture the logic by using the set value to propose. But it seems that the decision should be on the environment. **Start timeoutpropose also for the proposer**.
- [x] #161 E.g., consensus steps (e.g., NewRound) which are not defined in the arXiv paper are not aligned. Discuss alignment between step change in spec and code w.r.t. PrecommitAny check in the beginning in the spec
- [x] Test and logic for line 26
- [x] **Update: This is handled by adding the "step change" logic.** Handling of proposals for future rounds. Currently, when we receive a proposal for a future round we store it, but we don't call the consensus statemachine and we don't store a pending event. However, if we go to a round where we have already received the proposal, we need to execute line 22. I guess we need to 
    - [x] store a pending event (with the future round number).
    - [x] we need to update the pending check in `nextAction` to look for the current height/round only
    - [x] write a test

- [x] **Update: added https://github.com/informalsystems/malachite/issues/143 for Phase 2*** we should write invariants for agreement and validity and see whether `quint run` and `quint verify` can find something (also for cases with more than 1/3 faults)
